# Generated by Django 4.1.3 on 2022-12-01 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Country')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Article text')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Article created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Article updated at')),
                ('published', models.BooleanField(default=True, verbose_name='Article published')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Football player',
                'verbose_name_plural': 'Football players',
                'ordering': ['id'],
            },
        ),
    ]
